spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/astrosales_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970