spring:
  datasource:
    url: jdbc:postgresql://${DEV_HOST}:${DEV_PORT}/${DEV_DB_NAME}
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: ${JWT_SECRET}